% MATLAB Editor Run Commands
% @version 3
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name extractFeatures
%  @associatedFile /Users/kevinchau/ee20n/Lab 6: Shazam/extractFeatures.m
%  @mostRecentlyActioned false
%  @uniqueId -4ae937fe:1427e32c95f:-7fee

extractFeatures(filename, window_time, fs_target, print_len)

%% @name extractFeatures_2
%  @associatedFile /Users/kevinchau/ee20n/Lab 6: Shazam/extractFeatures.m
%  @mostRecentlyActioned true
%  @uniqueId -4ae937fe:1427e32c95f:-7fed

extractFeatures(tone.wave,.37, 4000, print_len)

%% @name extractFeatures
%  @associatedFile /Users/kevinchau/Documents/MATLAB/Lab 6: Shazam/extractFeatures.m
%  @mostRecentlyActioned false
%  @uniqueId 71332b3b:1427e66a122:-7fd8

extractFeatures('tone.wave', .37, 4000, 16)

%% @name extractFeatures_2
%  @associatedFile /Users/kevinchau/Documents/MATLAB/Lab 6: Shazam/extractFeatures.m
%  @mostRecentlyActioned true
%  @uniqueId 138b7123:14280cef400:-7ffc

extractFeatures('tone.wav', .37, 4000, 16)

%% @name generateQuery
%  @associatedFile /Users/kevinchau/Documents/MATLAB/Lab 6: Shazam/generateQuery.m
%  @mostRecentlyActioned true
%  @uniqueId 64101126:14280fa1b56:-7f9d

generateQuery('tone.wav', 30, .37, 4000, 16)

%% @name ber
%  @associatedFile /Users/kevinchau/Documents/MATLAB/Lab 6: Shazam/ber.m
%  @mostRecentlyActioned false
%  @uniqueId 4db4db69:1429070047a:-7fd8

ber(2, 3, 100)

%% @name ber_2
%  @associatedFile /Users/kevinchau/Documents/MATLAB/Lab 6: Shazam/ber.m
%  @mostRecentlyActioned true
%  @uniqueId 4db4db69:1429070047a:-7fd7

ber([2 3 4 5 7], [1 3 5 5 6], 100)

